language: node_js
node_js:
  - stable
  - "10.15.1"

env:
  global: CODECLIMATE_REPO_TOKEN=1e51a0bb707338df05c8a2de305dc78bbb864b9dc967fed81809009b37c13348
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run coverage
after_success:
  - npm run coverage
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT