language: node_js
node_js:
  - stable

env: 
  - CXX=g++-4.8

addons: 
  apt:
    sources:
      - ubuntu-toolchain-r-test

packages: 
  - g++-4.8
  
cache:
directories:
  - node_modules

install:
  - npm install
script:
  - npm run test


after_success:
  - npm run coverage
